name: User Service CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_USER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/socialmedia/user-service:son ./user-service
          docker push asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/socialmedia/user-service:son

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_USER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Deploy User Service
        run: |
          kubectl apply -f ./k8s/user-service.yaml
